sensu-server:
  image: hiroakis/docker-sensu-server
  ports:
    - "8086:8086"
    - "10022:22"
    - "3000:3000"
    - "4567:4567"
    - "5671:5671"
    - "15672:15672"
sensu-client:
  build: sensu-client/
  links:
    - sensu-server
